on:
  push:
    branches: [main]
    paths:
      - 'src/**'
  pull_request:
    branches: [main]
name: Process Content Artifacts
env:
  HOME_REPO: opencomply/oscal-content
  DEFAULT_REF: refs/heads/main
  OSCAL_VERSION: 1.0.0
  OSCAL_DIR_PATH: oscal
  CICD_DIR_PATH: oscal/build/ci-cd
  CONTENT_CONFIG_PATH: src/config
  SAXON_VERSION: 9.9.0-1
jobs:
  validate-and-publish-content:
    name: Validate and Publish Content
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: usnistgov/oscal
          fetch-depth: 1
          ref: v${{ env.OSCAL_VERSION }}
          path: ${{ env.OSCAL_DIR_PATH }}
          submodules: recursive

      - name: Install APT dependencies
        run: |
          sudo rm -rf /var/lib/apt/lists/* && sudo apt-get update
          sudo apt-get install libxml2-utils

      - name: Install NPM dependencies
        run: |
          sudo npm install --loglevel verbose -g yargs ajv-formats@"^1.5.x" ajv-cli@"^4.0.x" yaml-convert@"^1.0.x"

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Get Saxon-HE
        run: |
          mvn org.apache.maven.plugins:maven-dependency-plugin:2.10:get -DartifactId=Saxon-HE -DgroupId=net.sf.saxon -Dversion=${SAXON_VERSION}

      - name: Validate Content
        run: |
          bash "${{ github.workspace }}/${CICD_DIR_PATH}/validate-content.sh" -o "${{ github.workspace }}/${OSCAL_DIR_PATH}" -a "${{ github.workspace }}" -c "${{ github.workspace }}/${CONTENT_CONFIG_PATH}"

      - name: Convert Content
        run: |
          bash "${{ github.workspace }}/${CICD_DIR_PATH}/copy-and-convert-content.sh" -o "${{ github.workspace }}/${OSCAL_DIR_PATH}" -a "${{ github.workspace }}" -c "${{ github.workspace }}/${CONTENT_CONFIG_PATH}" -w "${{ github.workspace }}" --resolve-profiles

      - name: Commit Content
        if: github.repository == env.HOME_REPO && github.ref == env.DEFAULT_REF
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -sm "chore: auto-converted artifacts" || echo "No content to commit"

      - name: Publish Content
        uses: ad-m/github-push-action@master
        if: github.repository == env.HOME_REPO && github.ref == env.DEFAULT_REF
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
